import Head from 'next/head';
import { withAuth } from '@hoc/index';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>Init</main>
    </>
  );
};

export default withAuth(Home);
